### ISSUE TITLE
The sender is not displayed properly in table and JSON

### ISSUE THREAD

**Issue by soywod** [TornaxO7/himalaya#21]
- The sender is always fully displayed (the long form `Sender Name <sender@mail.com>`. Only the name should be displayed, and if no name exists then the email address.
- The right part of a sender can be encoded. You forgot to decode it (with the `rfc2047_decoder` lib)

For example, let's take `=?UTF-8?Q?Userame?= <user.name@mail.com>`. Himalaya's master branch shows `Username`, but your branch shows `=?UTF-8?Q?Userame?= <user.name@mail.com>`

**Comment by TornaxO7** [comment]
> The sender is always fully displayed (the long form Sender Name <sender@mail.com>. Only the name should be displayed, and if no name exists then the email address.

For which subcommand? I'd prefer it to always see the mail address of the sender as well! Otherwise it might be a little bit dangerous in my opinion. Suppose you mean that only the name should be displayed if you read a mail. What happens if the sender is actually someone suspicious but uses a name of one of your friends? Like: `Your Friend <unserious@mail.com>`. If we would only display the name, then we could be easily tricked.

(Or am I overthinking?)

> The right part of a sender can be encoded. You forgot to decode it (with the rfc2047_decoder lib)

Could you please explain me for which subcommand this happens?

**Comment by soywod** [comment]
As I put in the title, I'm talking about the list command (the plain table and the JSON). We need them to be compact (to take as few term width as possible). Everywhere else we should see the full address (and it's already the case, no need to touch).
