### ISSUE TITLE
Read

### ISSUE THREAD

**Issue by TornaxO7** [TornaxO7/himalaya#5]
- [x] The JSON output does not have the same shape (it misses `hasAttachment`)
- [x] The JSOn output should show the `text/html` version of the mail if no `text/plain` is found.

**Comment by TornaxO7** [comment]
@soywod Have you started to work on these two issues yet? If not, should I pick one? And  can you create a PR-Draft for this issue please for the kanban board?

**Comment by soywod** [comment]
I did not start yet, you can take both if you have time! Because I will work on the refactor as mentioned there https://github.com/TornaxO7/himalaya/issues/9#issuecomment-903125629.

**Comment by TornaxO7** [comment]
Alright, then I'll take over those two issues!

**Comment by TornaxO7** [comment]
@soywod I've got a question for the first task: Isn't it possible to create a key `attachments` for each message. So everyone just needs to look if the length of this list is greater than 0 to know if there are attachments or not.

**Comment by soywod** [comment]
Initially, I did not put the attachments for all messages because of perfs. To get informations about attachments you need to parse bodies, which implies a bigger IMAP request and longer parsing time. What could fix this is a caching system, but as I already explained this will move to a dedicated lib (see https://github.com/soywod/himalaya/discussions/118#discussioncomment-906315).

**Comment by TornaxO7** [comment]
Hold on. My fork here get's *everything* of a message, that also means all attachments of a message. Is this fine?

**Comment by soywod** [comment]
Well, we will see by usage. If it's too slow to show the message list, we will remove it!

**Comment by TornaxO7** [comment]
Closed due to [this](https://github.com/TornaxO7/himalaya/pull/11) PR.
